config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('voca/',include('voca.urls')),
]

voca/urls.py
from django.urls import path
from . import views

app_name='voca'

urlpatterns = [
    path('', views.index,name='index'),
    path('<int:word_id>/', views.detail, name='detail'),
    # url 매칭시 필요
    path('word/modify/<int:word_id>/', views.word_modify, name='word_modify'),
    # 단어 및 뜻 수정 시
    path('example/create/<int:word_id>/', views.example_create, name='example_create'),
    # 예문 작성 시
    path('word/create/', views.word_create, name='word_create'),
    # 단어 및 뜻 작성 시
    path('word/delete/<int:word_id>/', views.word_delete, name='word_delete'),
    # 단어 및 뜻 삭제 시
    path('example/delete/<int:example_id>/', views.example_delete, name='example_delete'),
    # 예문 삭제 시
]

voca/models.py
from django.db import models


class Word(models.Model):
    subject = models.CharField(max_length=100)
    meaning = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Example(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

voca/forms.py
from django import forms
from voca.models import Word,Example


class WordForm(forms.ModelForm):
    class Meta:
        model = Word
        fields = ['subject', 'meaning']

        labels = {
            'subject': '단어',
            'meaning': '뜻',
        }

class ExampleForm(forms.ModelForm):
    class Meta:
        model = Example
        fields = ['content']
        labels = {
            'content': '예문',
        }

voca/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Word, Example
from django.http import HttpResponseNotAllowed
from .forms import WordForm, ExampleForm
from django.contrib import messages

def index(request):
    word_list = Word.objects.order_by('-create_date')
    context = {'word_list': word_list}
    return render(request, 'voca/word_list.html', context)

def detail(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    context = {'word': word}
    return render(request, 'voca/word_detail.html', context)

def example_create(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    word.example_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('voca:detail', word_id=word.id)

def word_create(request):
    if request.method == 'POST':
        form = WordForm(request.POST)
        if form.is_valid():
            word = form.save(commit=False)
            word.create_date = timezone.now()
            word.save()
            return redirect('voca:index')
    else:
        form = WordForm()
    context = {'form': form}
    return render(request, 'voca/word_form.html', context)


def word_modify(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    if request.method == "POST":
        form = WordForm(request.POST, instance=word)
        if form.is_valid():
            word = form.save(commit=False)
            word.modify_date = timezone.now()  # 수정일시 저장
            word.save()
            return redirect('voca:detail', word_id=word.id)
    else:
        form = WordForm(instance=word)
    context = {'form': form}
    return render(request, 'voca/word_form.html', context)

def word_delete(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    word.delete()
    return redirect('voca:index')

def example_modify(request, example_id):
    example = get_object_or_404(Example, pk=example_id)
    if request.method == "POST":
        form = ExampleForm(request.POST, instance=example)
        if form.is_valid():
            example = form.save(commit=False)
            example.modify_date = timezone.now()
            example.save()
            return redirect('voca:detail', word_id=example.word.id)
    else:
        form = ExampleForm(instance=example)
    context = {'example': example, 'form': form}
    return render(request, 'voca/example_form.html', context)

def example_delete(request, example_id):
    example = get_object_or_404(Example, pk=example_id)
    example.delete()
    return redirect('voca:detail', word_id=example.word.id)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- voca CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, voca!</title>
</head>
<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'voca:index' %}">소프트웨어학과 32193049 이동원's voca</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/voca/word_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ word.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ word.meaning }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ word.create_date }}
                </div>
            </div>
            <div class="my-3">
            <a href="{% url 'voca:word_modify' word.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'voca:word_delete' word.id  %}">삭제</a>
        </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{word.example_set.count}}개의 예문이 있습니다.</h5>
    {% for example in word.example_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ example.content }}</div>
            <a href="#" class="delete btn btn-sm btn-outline-secondary " data-uri="{% url 'voca:example_delete' example.id  %}">삭제</a>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ example.create_date }}
                </div>
            </div>

        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'voca:example_create' word.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">예문</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>


        <input type="submit" value="새로운 예문 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/voca/word_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">새로운 단어 등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">단어</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="meaning" class="form-label">뜻</label>
            <textarea class="form-control" name="meaning"
                      id="meaning" rows="1">{{ form.meaning.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/voca/word_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>뜻</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if word_list %}
        {% for word in word_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'voca:detail' word.id %}">{{ word.subject }}</a>
            </td>
            <td>{{word.meaning}}</td>
            <td>{{ word.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">단어가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'voca:word_create' %}" class="btn btn-primary">새로운 단어 등록하기</a>
</div>
{% endblock %}